name: ${project.artifactId}
version: ${project.version}_${git.commit.id.abbrev}
author: aurgiyalgo
main: com.aurgiyalgo.TownyElections.TownyElections
depend: [Towny]
api-version: 1.14
commands:
  townyelections:
    description: Command for TownyElections info and management
    usage: /<command>
    aliases: telect
    permission: townyelections.use
  elections:
    usage: <command>
    permission: townyelections.elections
  party:
    usage: /<command>
    permission: townyelections.party
permissions:
  townyelections.*:
    default: op
    children:
      townyelections.use: true
      townyelections.vote.*: true
      townyelections.convoke.*: true
      townyelections.run.*: true
      townyelections.unvote.*: true
  townyelections.use:
    default: true
  townyelections.elections:
    default: true
  townyelections.parties:
    default: true
  townyelections.vote.*:
    description: Access to vote command
    default: op
    children:
      townyelections.vote.town: true
      townyelections.vote.nation: true
      townyelections.vote.towndecision: true
      townyelections.vote.nationdecision: true
  townyelections.convoke.*:
    default: op
    children:
      townyelections.convoke.town: true
      townyelections.convoke.nation: true
      townyelections.convoke.towndecision: true
      townyelections.convoke.nationdecision: true
  townyelections.run.*:
    default: op
    children:
      townyelections.run.town: true
      townyelections.run.nation: true
  townyelections.stop.*:
    default: op
    children:
      townyelections.stop.town: true
      townyelections.stop.nation: true
      townyelections.stop.towndecision: true
      townyelections.stop.nationdecision: true
  townyelections.unvote.*:
    default: op
    children:
      townyelections.unvote.town: true
      townyelections.unvote.nation: true
      townyelections.unvote.towndecision: true
      townyelections.unvote.nationdecision: true